name: Continuous Integration
run-name: Node.js CI
on:
  workflow_call: # required when creating a reusable workflow
#    inputs:
#      config-path:
#        required: false
#        type: string
#    secrets:
#      token:
#        required: false
jobs:
  check-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # TODO: use typescript compiler to validate code

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16 # originally using v14 but getting error. I believe using setup-node@v2 would allow older version

      - name: Install dependencies
        run: npm ci

      - name: Compile TypeScript
        run: npx tsc --listFiles

      - name: Lint Code
        run: npm run lint --if-present

      - name: Run Unit Tests
        run: npm run unit:tests

      #      - name: Run Error Handling Tests
      #        run: npm run test:error-handling

#      - name: Code Coverage
#        run: npm run test:coverage


#      - name: Run Redux/State Management Tests
#        run: npm run redux:tests
#
#      - name: Run Component Tests
#        run: npm run test:components
#
#      - name: Run End-to-End Tests
#        run: npm run test:e2e
#
#      - name: Run Snapshot Tests
#        run: npm run test:snapshot
#
#      - name: Run Routing Tests
#        run: npm run test:routing
#
#      - name: Run API Tests
#        run: npm run test:api
#
#      - name: Run Integration Tests
#        run: npm run test:integration


