import React from 'react';
import './globals.css';
import { Inter } from 'next/font/google';
import Navbar from '@/components/Navbar';
import SessionProvider from '@/components/SessionProvider';
import ReactQueryProvider from "@/components/ReactQueryProvider";
import { ThemeProvider } from '@mui/material/styles'; 
import CssBaseline from '@mui/material/CssBaseline'; //* CssBaseline kickstart an elegant, consistent, and simple baseline to build upon.
import theme from './theme'; 
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <ThemeProvider theme={theme}>
      <CssBaseline /> 
      <AppRouterCacheProvider>
        <html lang="en">
          <body className={inter.className}>
            <ReactQueryProvider>
              <SessionProvider>
                <Navbar />
                {children}
              </SessionProvider>
            </ReactQueryProvider>
          </body>
        </html>
      </AppRouterCacheProvider>
    </ThemeProvider>
  );
}
