import React from 'react';
import './globals.css';
import { Inter } from 'next/font/google';
import Navbar from '@/components/Navbar';
import SessionProvider from '@/components/SessionProvider';
import ReactQueryProvider from "@/components/ReactQueryProvider";
import { ThemeProvider } from '@mui/material/styles'; 
import theme from './theme'; 
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';
import CssBaseline from '@mui/material/CssBaseline';
import Head from 'next/head';

const inter = Inter({ subsets: ['latin'] });

//defining the Metadata type
type Metadata = {
  title: string;
  description: string;
  imageUrl?: string;
  metadataBase: URL;
};

export const metadata: Metadata = {
  title: 'NSC Events',
  description: 'Generated by create next app',
  metadataBase: new URL ('https://next-learn-dashboard.vercel.sh'),
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <ThemeProvider theme={theme}>    
      <AppRouterCacheProvider>
      <Head>
        <title>{metadata.title}</title>
        <meta charSet="utf-8" />
        <meta name="viewport" content="initial-scale=1.0, width=device-width" />
        <meta name="description" content={metadata.description}/>
        <link rel="canonical" href="http://www.yoursite.com/example" />
        <meta property="og:title" content={metadata.title} />
        <meta property="og:description" content={metadata.description} />
        <meta property="og:image" content={metadata.imageUrl} />
        <meta property="og:type" content="website" />
        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:title" content={metadata.title} />
        <meta name="twitter:description" content={metadata.description} />
        <meta name="twitter:image" content={metadata.imageUrl} />
        <link rel="icon" href={metadata.imageUrl} />
      </Head>

        <html lang="en">
          <body className={inter.className}>
            <ReactQueryProvider>
              <SessionProvider>
                <Navbar />
                <CssBaseline />
                {children}
              </SessionProvider>
            </ReactQueryProvider>
          </body>
        </html>
      </AppRouterCacheProvider>
    </ThemeProvider>
  );
}
