export const EventTags: string[] = [
    "Professional Development",
    "Club",
    "Social",
    "Tech",
    "Cultural",
    "Study",
    "Coffee",
    "Art/Creative",
    "Conference",
    "Craft",
    "Networking",
    "Pizza",
    "Free Food",
    "LGBTQIA",
];