name: Auto-assign Issue

on:
  issues:
    types: [opened]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - uses: pozil/auto-assign-issue@v1.14.0
        with:
          assignees: ${{ context.actor }}
