name: Auto-assign Issue

on:
  issues:
    types: [opened]

permissions:
  issues: write  # Grant write permission to manage issues
  
jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.AUTO_ASSIGN_ISSUE_TOKEN }}
          script: |
            github.issues.addAssignees({
              issue_number: context.issue.number,
              assignees: [context.actor]
            })
