name: Auto-assign Issues

on:
  issues:
    types: [opened]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            github.issues.addAssignees({
              issue_number: context.issue.number,
              assignees: [context.actor]
            })
