name: Auto-assign Issue

on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - uses: pozil/auto-assign-issue@v1
        with:
          repo-token: ${{ secrets.AUTO_ASSIGN_ISSUE_TOKEN }}
          assignees: ${{ github.actor }}
