name: Auto-assign Issue

on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/issues-assign@v5
        with:
          github-token: ${{ secrets.AUTO_ASSIGN_ISSUE_TOKEN }}
          assignees: ${{ github.actor }}
