# CD workflow to deploy app to staging environment.
# Defines one job - deploy-to-staging.
# Job runs on ubuntu-latest runner.
#  Steps:
#   - Download build artifact
#   - Run CD script to deploy app to production
# Workflow is reusable and triggered via workflow_call.
# Can pass inputs and secrets.

name: Node.js CD Staging
run-name: Node.js CD (staging)
on:
  workflow_call: # required when creating a reusable workflow
#    inputs:
#      config-path:
#        required: false
#        type: string
#    secrets:
#      token:
#        required: false
jobs:
  deploy-to-staging:
    runs-on: ubuntu-latest
    steps:
      #      - name: Download build
      #          uses: actions/download-artifact@v3
      #          with:
      #            name: next.js-build

      - name: Run CD for Staging
        run: |
          echo Perform deployment steps for the staging environment