name: CI-CD Staging Workflow
run-name: CI-CD Staging

# runs when a branch is pushed to main or merged. The closing of the PR triggers the event and the if statements check
# whether the branch was merged or not before running the CI and CD jobs
on:
  push:
    branches: [ "staging"]

  create:

  pull_request:
    branches: [ "staging" ]

    types:
      - closed

jobs:

  CI:
    uses: ./.github/workflows/ci.yml # reusable workflow file path


  CD:
    uses: ./.github/workflows/cd.yml # reusable workflow file path
    needs: CI
    if: github.event.pull_request.merged == true || github.event_name == 'push'


