name: CI-CD Staging Workflow
run-name: CI-CD Staging

# runs when a branch is pushed to staging or merged. The closing of the PR triggers the event and the if statements check
# whether the branch was merged or not before running the CD jobs. CI runs on PR closed if PR was merged into staging
on:
  push:
    branches: [ "staging"]

  pull_request:
    branches: [ "staging" ]

    types:
      - closed

jobs:
  # TODO: discuss whether this should run here because on successful CI run it will be merged from develop. Essentially
  #  calling it 2x
  CI:
    uses: ./.github/workflows/ci.yml # reusable workflow file path


  CD:
    uses: ./.github/workflows/cd.yml # reusable workflow file path
    needs: CI
    if: github.event.pull_request.merged == true || github.event_name == 'push'


